allowBuilds:
  simple-git-hooks: true
  unrs-resolver: true

overrides:
  undici: 7.28.0

onlyBuiltDependencies:
  - simple-git-hooks

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
