---
name: CI

'on':
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true

jobs:
  lint-renovate:
    name: Validate Renovate presets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - default
          - personal
          - archived-repository
    timeout-minutes: 10
    env:
      LOG_LEVEL: debug
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 'lts/*'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check formatting
        run: yarn check-format

  release:
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    name: Release
    needs: [lint-renovate, lint]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 'lts/*'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - env:
          GIT_AUTHOR_EMAIL: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'mrbro-bot[bot]'
          GIT_COMMITTER_EMAIL: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'mrbro-bot[bot]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Semantic Release
        run: yarn semantic-release
