---
name: CI

'on':
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true

jobs:
  lint-renovate:
    name: Validate Renovate presets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - default
          - archived-repository
    timeout-minutes: 10
    env:
      LOG_LEVEL: debug
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 'lts/*'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check formatting
        run: yarn check-format

  release:
    env:
      DRY_RUN: true
    name: Release
    needs: [lint-renovate, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Get Wokrflow Application Token
        id: get-workflow-app-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'contents:write, issues:write, pull_requests:write'

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-workflow-app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 'lts/*'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Get Release Options
        env:
          INPUT_DRY_RUN: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.dry_run && 'true' || 'false' }}
          IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: |
          if [[ $INPUT_DRY_RUN != 'true' || $IS_DEFAULT_BRANCH == 'true'  ]]; then
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - env:
          GIT_AUTHOR_EMAIL: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'mrbro-bot[bot]'
          GIT_COMMITTER_EMAIL: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'mrbro-bot[bot]'
          GITHUB_TOKEN: ${{ steps.get-workflow-app-token.outputs.token }}
        name: Semantic Release
        run: yarn semantic-release --dry-run ${{ env.DRY_RUN }}
