name: ci

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  LOG_LEVEL: debug

jobs:
  lint-renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - default
          - onboarding
          - personal
          - archived-repository
          # - .github/renovate   # is validated by `renovate` during loading for each preset.
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator
