---
# Renovate this repository if Renovate-specific tasks are checked or if dispatched.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches-ignore: [main]
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for Renovate
        required: false
        type: string
        default: 'debug'
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [main]

permissions:
  contents: read

jobs:
  renovate:
    if: >-
      (github.event.action == 'edited' && !contains(github.actor, '[bot]')) ||
      (
        github.event_name != 'workflow_run' ||
        github.event.workflow_run.conclusion == 'success'
      )
    name: Renovate
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate.yaml@1c4d83598115c2fee5f97913f7a9b62bb1421b63 # v3.0.5
    with:
      log_level: ${{ inputs.log-level || 'debug' }}
      path_filters: >-
        [
          '.github/workflows/renovate.yaml',
          '.github/renovate.json5',
          'archived-repository.json',
          'default.json',
          'onboarding.json',
          'personal.json',
        ]
      print_config: ${{ inputs.print-config || false }}
