---
# Renovate this repository if Renovate-specific tasks are checked or if dispatched.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for Renovate
        required: false
        type: string
        default: 'debug'
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  renovate:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    name: Renovate
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/renovate.yaml@d6612ed3d94d04df69e773610adf946a74089dbc # v1.11.2
    with:
      log_level: ${{ inputs.log-level || 'debug' }}
      path_filters: >-
        "[
          '.github/workflows/renovate.yaml',
          '.github/renovate.json5',
          'archived-repository.json',
          'default.json',
          'onboarding.json',
          'personal.json',
        ]"
      print_config: ${{ inputs.print-config || false }}
